name: atena
description: "Gerencie suas tarefas"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: 3.0.0-dev.17
  go_router: ^16.0.0
  dio: ^5.8.0+1
  sqflite: ^2.4.2
 # flutter_background_service: ^5.1.0
  flutter_riverpod: ^3.0.0-dev.16
  flutter_dotenv: ">=5.2.1 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ">=0.7.5 <0.9.0"
  riverpod_lint: ^3.0.0-dev.16

flutter:
  uses-material-design: true
  assets:
    - env/



