name: test

on:
  push:
    branches: [ dev, main, clean ]
  pull_request:
    branches: [ dev, master, clean ]

jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle 9.0.0
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.0.0
          cache-read-only: false

      - name: Setup GraalVM 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run all the Tests
        run: gradle clean check -Dtest.profile=integration
        env:
          BASIC_PASSWORD: ${{ secrets.BASIC_PASSWORD }}
          BASIC_USERNAME: ${{ secrets.BASIC_USERNAME }}

          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
          TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}

          TEST_JWT_ISSUER: ${{ secrets.TEST_JWT_ISSUER }}
          TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          TEST_PUBLIC_KEY: ${{ secrets.TEST_PUBLIC_KEY }}

          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_USER: ${{ secrets.REDIS_USER }}

      - name: Try to make a jvm build
        run: gradle clean build -x test
        env:
          BASIC_PASSWORD: ${{ secrets.BASIC_PASSWORD }}
          BASIC_USERNAME: ${{ secrets.BASIC_USERNAME }}

          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
          TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}

          TEST_JWT_ISSUER: ${{ secrets.TEST_JWT_ISSUER }}
          TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          TEST_PUBLIC_KEY: ${{ secrets.TEST_PUBLIC_KEY }}

          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_USER: ${{ secrets.REDIS_USER }}
