version: 2
updates:
  - package-ecosystem: gradle
    directory: "./atena-backend"
    schedule:
      interval: daily

  - package-ecosystem: pub
    directory: "./atena-app"
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
