name: Test and Build the App

on:
  push:
    paths:
      - 'atena-app/**'
      - '.github/workflows/app-workflow.yml'
  pull_request:
    paths:
      - 'atena-app/**'
      - '.github/workflows/app-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test
