name: Test and Build the App

on:
  push:
    paths:
      - 'atena-app/**'
      - '.github/workflows/app-workflow.yml'
  pull_request:
    paths:
      - 'atena-app/**'
      - '.github/workflows/app-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./atena-app
    steps:
      - uses: actions/checkout@v5

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.1
          cache: true

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: ./
          key: ${{ runner.os }}-primes
      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
