name: test

on:
  push:
    paths:
      - 'atena-backend/**'
      - '.github/workflows/backend-workflow.yml'
  pull_request:
    paths:
      - 'atena-backend/**'
      - '.github/workflows/backend-workflow.yml'

jobs:
  test:

    name: Test and Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./atena-backend

    steps:
      - name: Setup checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle 9.0.0
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.0.0
          cache-read-only: false

      - name: Run all the Tests
        run: gradle clean check -Dtest.profile=integration
        env:
          BASIC_PASSWORD: ${{ secrets.BASIC_PASSWORD }}
          BASIC_USERNAME: ${{ secrets.BASIC_USERNAME }}

          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}


      - name: Try to make a jvm build
        run: gradle clean build -x test
        env:
          BASIC_PASSWORD: ${{ secrets.BASIC_PASSWORD }}
          BASIC_USERNAME: ${{ secrets.BASIC_USERNAME }}

          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

